### ISSUE TITLE
Numbered list disappears in ODT

### ISSUE THREAD

**Issue by fpoto** [LarsGit223/dokuwiki-plugin-odt#160] opened 2016-08-18 15:00 UTC
I have a short page with titles, underlining, bold, links, footnotes and a numbered list.
In ODT, links are shown underlined but they are not active.
Most importantly, the numbered list simply disappears: text before and after the numbered list is present, but not the numbered list itself.

**Comment by LarsGit223** [comment] 2016-08-18 15:50
Please provide example wiki page code which I can use to reproduce the problem.

**Comment by fpoto** [comment] 2016-08-22 11:39
[a.txt](https://github.com/LarsGit223/dokuwiki-plugin-odt/files/429981/a.txt)
Here you are.

**Comment by LarsGit223** [comment] 2016-08-22 16:01
Hmmm...I did a test export without any problems.
I tested with the current development/master branch and the latest release. Both versions export the list correctly.

If you are not using the latest version, please update and re-test. If you are using the latest version already or if it still fails after the update then please provide a screenshot of the ODT plugin config settings on your server. Thanks in advance.

**Comment by fpoto** [comment] 2016-08-23 13:21
Version is 2016-08-14
![screenshot at 2016-08-23 15-18-40](https://cloud.githubusercontent.com/assets/5763468/17893210/219fffa8-6945-11e6-8847-e2c7572aec69.png)

**Comment by LarsGit223** [comment] 2016-08-23 18:37
Even with your config settings and release 2016-08-14 and the content in a.txt I can't reproduce the problem.

Let's try this:
Please export an example page with the error and upload it or provide a download link for me. Please only save the exported ODT document. Do not open it - otherwise e.g. LibreOffice might already change the document on opening it.

Maybe I can see the problem from the faulty generated ODT document XML code. Thanks in advance.

**Comment by fpoto** [comment] 2016-08-24 13:38
I made <http://wiki.potorti.it/playground/playground/odtbug> editable to @ALL for you to check by yourself, should that help.

Here is the produced odt: [playground-playground-odtbug.zip](https://github.com/LarsGit223/dokuwiki-plugin-odt/files/434811/playground-playground-odtbug.zip)

**Comment by LarsGit223** [comment] 2016-08-24 17:24
Ok. The List is completely not present in the exported ODT document. I thought the XML code of the ODT document might be malformed and therefore the list is not visible.

But now I think the problem is something else. Which DokuWiki plugins do you have installed on your server?
Any list plugins? (e.g. yalist per default does not support ODT export!)

**Comment by fpoto** [comment] 2016-08-25 12:44
Found it. The cuplrit is the "Simple universal list plugin" (https://www.dokuwiki.org/plugin:yalist) which I insstalled but never used. Nonetheless, if it is enabled causes this problem. The comments in the doc page speak about added ODT support, but in fact it does not work, as mentioned in their issue list.

Well, this means that plugin compatibility in Dokuwiki is an open problem...

Thanks for your assistance

**Comment by LarsGit223** [comment] 2016-08-25 16:33
The ODT support in the yalist plugin worked in the past only if you manually added the sourcecode mentioned on the yalist plugin page. But this code is old and does not work with current ODT versions. And as you noticed, it was never included in the yalist release which you install/download.

In this case I would not call it a compatibility issue. Every syntax plugin needs to be extended if it wants to support ODT. In this case it's simply not supported.

But anyway, I'm actually working on ODT support for the yalist plugin but it is not finished yet.
As this was a problem of the yalist plugin I will close this ticket now.

**Closed by LarsGit223** 2016-08-25 16:33 UTC

**Comment by LarsGit223** [comment] 2016-08-27 14:56
I just created a pull-request for the yalist plugin to implement ODT support, see https://github.com/mprins/dokuwiki-yalist-plugin/pull/9.

**Comment by fpoto** [comment] 2016-08-29 08:49
Thanks
