### ISSUE TITLE
Error in content.xml when using refnote, yalist plugins

### ISSUE THREAD

**Issue by tomtroughton** [LarsGit223/dokuwiki-plugin-odt#155] opened 2016-08-12 08:16 UTC
When I export a page using the yalist and refnote plugins, I get an error in the content.xml. There are notes in the list, so I am not sure where the problem lies. The error message is:

> XML Parsing Error: mismatched tag. Expected: /text:p.
> Location: file:///home/tom/Desktop/content.xml
> Line Number 60, Column 3309:

The line just breaks here, and continues on line 61, where the tag appears.

EDIT: I have applied the yalist patch from the wiki page. Using Elenor of Tsort, Xubuntu 16.04, php7, and all is up to date.

**Comment by LarsGit223** [comment] 2016-08-12 17:04
I checked the yalist plugin and it seems even though it does not support ODT export it can still break an exported ODT document. Checkout this piece of example wiki code from the yalist plugin page:
```
  : This definition list has DD tags without any preceding DT tags.
  : Hey, it's legal XHTML.
  ? Just like DT tags without following DD tags.
  ?? But DT tags can't contain paragraphs. That would __not__ be legal XHTML.
  .. If you try, the result will be rendered oddly.
```
If you try to export it, you will get a broken document. In this case the problem is the underlined **__not__**. If you discard the underlines then the example can be exported.

**Comment by LarsGit223** [comment] 2016-08-12 17:11
I also did some little tests with the refnotes plugin. It also does not support ODT export but does not seem to break the document.

**Comment by tomtroughton** [comment] 2016-08-12 18:16
Thank you.

**Comment by LarsGit223** [comment] 2016-08-27 14:57
I just created a pull-request for the yalist plugin to implement ODT support, see https://github.com/mprins/dokuwiki-yalist-plugin/pull/9.

**Comment by LarsGit223** [comment] 2017-01-27 18:59
The pull-request has been merged, so I close this now.

**Closed by LarsGit223** 2017-01-27 18:59 UTC
