### ISSUE TITLE
exported images are just sized of some little pixels

### ISSUE THREAD

**Issue by erdoukki** [LarsGit223/dokuwiki-plugin-odt#11] opened 2014-10-30 10:43 UTC
The exported images of the resulting .odt are smallest as possible.
Not the real size but only some pixels.

Opening the .odt into OpenOffice or LibreOffice and with zooming the image can be resized.

**Comment by LarsGit223** [comment] 2015-04-28 20:06
Hello,

I tried exporting to ODT with the DokuWiki example image ( {{wiki:dokuwiki-128.png}} ). If I export that to ODT the image size is OK. I also used LibreOffice (Version 4.2.8.2, Ubuntu, DokuWiki Hrun).

What happens on your installation if you export the DokuWiki image. Is the size OK?

Regards,
Lars

**Comment by LarsGit223** [comment] 2015-05-09 12:24
Hi!
I think I found your problem.
I did a fix which I just released. So as soon as you update to release 2015-05-09 the problem should disappear.

The problem only occured on re-sized images e.g. if you append '?128x128' to a picture link. This is fixed now. I will close this issue now. If you still have trouble, please re-open it.

Regards,
Lars

**Closed by LarsGit223** 2015-05-09 12:24 UTC
Labels: bug, help wanted

**Comment by dlukes** [comment] 2016-07-27 13:32
Hi, I'm experiencing a regression on this with the current release (2016-04-23). I've reverted to 2015-05-09 (the release which included the bugfix for this issue) and everything is working fine there.

**Comment by LarsGit223** [comment] 2016-07-27 14:11
Can you do me a favor and maybe test the current master branch?
I have written some unit test code for images and that says everything is fine at least in the current master/development branch.

If you get the problem also with the master branch then please specify how the wiki code for the image looks. Thanks.

**Comment by dlukes** [comment] 2016-07-27 14:12
OK, on it :)

**Comment by dlukes** [comment] 2016-07-27 15:08
I initially thought it was the same problem as before (re-sizing images by appending `?...x...`), and it's definitely related, but there may some more subtle interaction going on with the images.

Here's a MWE:

```
{{img:obr1.gif?763x401}}

{{img:obr3.gif?545x508}}
```

You can get the referenced images [from here](https://owncloud.korpus.cz/s/eNf1DVd7mydsBbh).

This is what `imagemagick` has to say about them:

```sh
$ identify obr1.gif
obr1.gif GIF 763x401 763x401+0+0 8-bit PseudoClass 32c 20.9KB 0.000u 0:00.000
$ identify obr3.gif
obr3.gif GIF 545x508 545x508+0+0 8-bit PseudoClass 32c 54.3KB 0.000u 0:00.000
```

You'll notice that the size specifications in the dokuwiki markup are actually the same as the original sizes of the pictures; that's because the dokuwiki markup was generated by conversion from legacy HTML sources, which in turn were (probably) made in a WYSIWYG editor which stored these explicitly.

# Current master (6e73cc5)

1. When I export the MWE as ODT, `obr1.gif` has some height but essentially zero width, while `obr3.gif` turns out OK. The ordering doesn't matter, if I swap them, the result is the same.
2. If I **remove the size specifications**, `obr1.gif` now comes out OK except that proportions are lost, whereas `obr3.gif` is rendered tiny but proportional.

# 2015-05-09

1. Images are sized as specified after the `?`.
2. Same behavior as in current master.

Hard to say where the problem is, since the format of the two images is pretty much identical (see output of `identify` above). The only thing that comes to mind is that their aspect ratios are different, but is it even possible that that would be the root cause...?

**Comment by LarsGit223** [comment] 2016-08-09 18:35
@dlukes:

sorry for the long delay but I was on vacation.

Thanks for the detailed problem description.
I did some tests but unfortunately did not get the same results as you did. In my tests your images had a normal size no matter if I specify a size via ? or not.

Anyway I noticed two things:
- the size of images is not the original size if you specify the same size as the original image size using ?
- if you specify a image size via ? the the image can become larger than the page


But I did a little change to fix the two points above anyway. I assume it does not solve your problem.

Could you please test the result anyway?
Therefore you would have to manually install the ODT plugin from the URL **https://github.com/LarsGit223/dokuwiki-plugin-odt/archive/images.zip**.

If it does not help we need to find out whats different in your case.

**Comment by dlukes** [comment] 2016-08-10 15:38
> sorry for the long delay but I was on vacation.

No need to apologize :) Thanks for taking a look at the issue!

> Could you please test the result anyway?
> Therefore you would have to manually install the ODT plugin from the URL https://github.com/LarsGit223/dokuwiki-plugin-odt/archive/images.zip.

With your fix I now get the behavior described under bullet 2. above in both cases -- i.e. irrespective of whether I specify the size or not using the `?`, the first image comes out normally sized but unproportional, whereas the second one is tiny but (probably, hard to tell given the small size) proportional.

If you can't reproduce it, I was thinking we might leave the issue alone -- it might as well be a weird quirk of the setup on my server...

**Comment by LarsGit223** [comment] 2016-08-10 15:52
Well, I did not get other issue reports about this but that does not mean that other people have not got the problem to. So I do not wan to give up yet.

Some more questions:
- could you provide a screenshot of the ODT plugin configuration on your server?
- what office software do you use to open the document, e.g. LibreOffice?

**Comment by dlukes** [comment] 2016-08-11 08:02
Yeah, sure, fine by me :) If you're willing to spend time on this, then great!

Here are the settings:

[![odt_settings.png](https://s10.postimg.org/x0j86dzix/odt_settings.png)](https://postimg.org/image/62pb4nevp/)

And I've viewed the result in LibreOffice 5 both on Linux and Mac. I've also tried the current Word for Mac, but it wasn't able to open the file.

**Comment by dlukes** [comment] 2016-08-11 08:06
Oh and here's the [generated document](https://owncloud.korpus.cz/s/ZnmylIPgekWNQda) for good measure :)

**Comment by LarsGit223** [comment] 2016-08-11 18:59
I did a change on the images branch so please re-test after re-installing from URL **https://github.com/LarsGit223/dokuwiki-plugin-odt/archive/images.zip**.

The reason for the problem seems to be a comma in the width of the first picture. The frame for the first picture had the following size attributes:
```svg:width="610,4pt" svg:height="401pt"```

The frame of the second picture  had the following size attributes:
```svg:width="436pt" svg:height="508pt"```

After I manually changed the **comma** to a **dot** the picture was displayed with a normal width.

**Comment by dlukes** [comment] 2016-08-12 08:18
Confirmed, this fixes it, thank you so much! :)

**Comment by dlukes** [comment] 2016-08-12 08:54
So it definitely looks like the root cause is the locale (`_odtGetImageSize` is lifted [from here](https://github.com/LarsGit223/dokuwiki-plugin-odt/blob/65fea3835267507aea90c141d7833b068768ff17/renderer/page.php#L3000):

```php
<?php
setlocale("LC_ALL", "cs_CZ.UTF-8");

function _odtGetImageSize($src, $maxwidth=NULL, $maxheight=NULL){
  if (file_exists($src)) {
    $info  = getimagesize($src);
    if(!$width){
      $width  = $info[0];
      $height = $info[1];
    }else{
      $height = round(($width * $info[1]) / $info[0]);
    }
    if ($maxwidth && $width > $maxwidth) {
      $height = $height * ($maxwidth/$width);
      $width = $maxwidth;
    }
    if ($maxheight && $height > $maxheight) {
      $width = $width * ($maxheight/$height);
      $height = $maxheight;
    }
    // Convert from pixel to centimeters
    if ($width) $width = (($width/96.0)*2.54);
    if ($height) $height = (($height/96.0)*2.54);
    return array($width, $height);
  }
  return array(0, 0);
}

$size1 = _odtGetImageSize("obr1.gif");
echo $size1[0]." cm; ", $size1[1]." cm";
?>
```

Output:

```
20,187708333333 cm; 10,609791666667 cm
```

Maybe this calls for a more systematic fix, because it could be breaking more stuff than we're currently aware of? I'm just wondering, I know very little php and I'm not acquainted with the ODT plugin's architecture, so I don't really know if it's possible / reasonable e.g. to just add `setlocale("LC_NUMERIC", "C");` to force the dot as decimal separator...

**Comment by Klap-in** [comment] 2016-08-12 11:29
If you add `?do=check` to the url of your wiki, do you see in the listed info some remarks about locale settings? If I remember right, there was already added some info about this, or maybe also a note/warning in this check-info..

**Comment by dlukes** [comment] 2016-08-12 12:10
> If you add ?do=check to the url of your wiki, do you see in the listed info some remarks about locale settings?

It says "Valid locale cs_CZ.UTF-8 found.", and all results are green / blue (success / info).

**Comment by LarsGit223** [comment] 2016-08-12 15:26
Thanks for the hint but what exactly would ```setlocale("LC_ALL", "cs_CZ.UTF-8");``` do?
I mean would it just change the locale for the one source file or for all files (I mean dokuwiki in total/other plugins)?

**Comment by LarsGit223** [comment] 2016-08-12 15:41
Found the following warning on http://php.net/manual/en/function.setlocale.php:

> The locale information is maintained per process, not per thread. If you are running PHP on a multithreaded server API like IIS, HHVM or Apache on Windows, you may experience sudden changes in locale settings while a script is running, though the script itself never called setlocale(). This happens due to other scripts running in different threads of the same process at the same time, changing the process-wide locale using setlocale().

So maybe we shouldn't use setlocale.

**Comment by dlukes** [comment] 2016-08-12 18:22
> what exactly would `setlocale("LC_ALL", "cs_CZ.UTF-8");` do?

That was just to simulate my environment; I was suggesting `setlocale("LC_NUMERIC", "C");` to force dot as decimal separator during document generation. But as you point out...

>> other scripts running in different threads of the same process at the same time, changing the process-wide locale using setlocale().
> So maybe we shouldn't use setlocale.

That was precisely what I had in mind when I said I know very little php :) So like you say, this is clearly not the way to go.

My point was just that php's implicit locale-aware stringification might be wreaking havoc in other places as well when the results are expected to have a decimal dot but come out with a comma, so I thought it'd be a good idea to look for a more systemic way of fixing this. But maybe there's no such silver bullet and it'll just have to be fixed individually in the relevant places if and when further bugs crop up :)

**Comment by LarsGit223** [comment] 2016-08-12 19:44
It was a good hint anyway. But for now like you said I think I better respect the warning and keep the fix at it is. Being aware of the problem will definitely help me in the future.

Thanks for reporting the issue and delivering the data and detailed descriptions. Thank You!

**Comment by dlukes** [comment] 2016-08-12 19:49
The pleasure was all mine :) Cheers!

**Comment by LarsGit223** [comment] 2016-08-14 13:55
@dlukes:
I just published a maintenance release which also includes the fix for your problem.

**Comment by dlukes** [comment] 2016-08-14 16:48
Thanks, got it!
