### ISSUE TITLE
Doesn't export nested table within a list using WRAP plugin

### ISSUE THREAD

**Issue by limelime** [LarsGit223/dokuwiki-plugin-odt#71] opened 2015-09-07 20:09 UTC
I don't know whether to create an issue in WRAP plugin or here.
dokuwiki-plugin-odt doesn't export nested table within a list using WRAP plugin.
Example:
```
    - Test nested table using WRAP.
    - Enter the following informations:<WRAP>
^ Field      ^ Value  ^
| Firstname  | John   |
| Lastname   | Smith  |
</WRAP>
    - Click on Save.
```

**Comment by LarsGit223** [comment] 2015-09-08 05:33
There is limited support for formatting inside WRAP boxes. I will have a closer look at it this evening and come back to you.

Is that working if you do it outside a list? E.g.
```
<WRAP>
^ Field      ^ Value  ^
| Firstname  | John   |
| Lastname   | Smith  |
</WRAP>
```

**Comment by limelime** [comment] 2015-09-08 14:12
Yes, it is working outside of the list.

**Comment by LarsGit223** [comment] 2015-09-08 17:44
Ok, I found out what the problem is:
The table is output inside of the list item (as expected). But this doesn't seem to be supported by the ODT format or by LibreOffice. I still have to check that.

So  for example if you insert a table in a list inside of LibreOffice, then it will split the list into two lists with a separate table in between the two lists. The only thing it does is telling the second list to continue numbering. But if you look at the ODT XML code you can see that it's two separate lists.

Not nice. I will have to check this in more detail. Sorry, I can't provide a quick fix for this. But I will have a further look on it and I will keep you posted.

**Comment by LarsGit223** [comment] 2015-09-08 21:26
Just checked the ODT specification:
A table element can not be nested in a list element, so I can just implement it the way LibreOffice does.

**Closed** 2015-09-13 13:12 UTC

**Comment by LarsGit223** [comment] 2015-09-13 13:14
Should be fixed., please test.

There is one little issue as mentioned before:
the table will not be indented as the list item in which it is included.

**Comment by LarsGit223** [comment] 2015-09-13 13:20
I opened another issue to keep track of the indention problem, see #73.

**Comment by LarsGit223** [comment] 2015-09-16 19:19
Any feedback? Is this working with your documents also?

**Comment by limelime** [comment] 2015-09-16 19:36
It is working on the 1st level of the list but it doesn't work on nested list.

```
~~NOCACHE~~
    - Test nested table using WRAP.
    - Enter the following informations:<WRAP>
^ Field      ^ Value  ^
| Firstname  | John   |
| Lastname   | Smith  |
</WRAP>
    - Click on **Save**.
    - Then do the followings:
      - Press something.
      - Add the following values:<WRAP>
^ Field      ^ Value  ^
| Firstname  | John-Nested list   |
| Lastname   | Smith-Nested list  |
</WRAP>
      - Click on Save.



  - Another list<WRAP>
^ Field      ^ Value  ^
| Firstname  | John   |
| Lastname   | Smith  |
</WRAP>
  - Another item

```

**Comment by limelime** [comment] 2015-09-22 13:57
Since you closed this issue, should I create a new issue with the above mentioned problem?

**Comment by LarsGit223** [comment] 2015-09-22 16:09
Yes, I would prefer that. Then we have everything neatly sorted.
