### ISSUE TITLE
support for new version bookcreator

### ISSUE THREAD

**Issue by Klap-in** [LarsGit223/dokuwiki-plugin-odt#141] opened 2016-04-27 22:55 UTC
Bookcreator has new backend based at localStorage of browsers.

To use ODT plugin in new version of bookcreator an update of ODT plugin is needed.
more details at https://github.com/Klap-in/dokuwiki-plugin-bookcreator/pull/72

**Comment by LarsGit223** [comment] 2016-04-28 17:11
I had a look at that but don't really see what to do.
Can you give me a hint. There are a lot of changes (28 files).

What needs to be done?

**Comment by LarsGit223** [comment] 2016-04-28 19:02
Just did some first tests with my merged master and your bookcreator/localstorage branch. Seems to work. Is there anything specific you like me to test?

**Comment by Klap-in** [comment] 2016-04-28 20:20
I did tests now mainly with Chrome, and a bit with Firefox on linux. If you have the possibility to test with Internet Explorer and others, could you test them please?
At the moment I'm adding acl checks. That is something that is not yet ok in this development version.

**Comment by LarsGit223** [comment] 2016-04-28 20:35
I did test with Firefox on Ubuntu.
As my wiki runs on Ubuntu I can't test with Internet Explorer, sorry.

I will see what other browsers I can check on Ubuntu.

The layout of the box around the icons on the wiki page was a bit itchy. I mean the box was too small. But I guess that's just a template issue. Will check tomorrow. Cheers.

**Comment by Klap-in** [comment] 2016-04-28 21:23
No idea what you mean with the 'box around the icons'. Could you please provide a snapshot of it?

**Comment by LarsGit223** [comment] 2016-04-29 19:36
It seems to be a template problem.
Here a snapshot from bootstrap3 template:

![bookcreator_bootstrap3](https://cloud.githubusercontent.com/assets/9009011/14927448/39b4511e-0e52-11e6-981c-0eafd0de8fcf.png)

It seems to be correct in the dokuwiki template:

![bookcreator_dokuwiki](https://cloud.githubusercontent.com/assets/9009011/14927467/5a43f6a0-0e52-11e6-83a6-3d73f5b81e0a.png)

**Comment by Klap-in** [comment] 2016-04-29 20:15
Before this update the bookbar box was displayed fine? (I simplified the css a bit, but maybe a bit too much)

**Comment by LarsGit223** [comment] 2016-04-29 20:36
Just downgraded to the offical version of bookcreator and went back to bootstrap3 template. The problem is still there. So you're safe I would say :relieved:

**Closed** 2016-08-11 12:38 UTC
Labels: enhancement
